name: complex_ui
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  build_runner: ^1.7.3

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.1
  google_sign_in: ^4.1.1
  provider: ^4.1.2
  cloud_firestore: ^0.13.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/app/
    - assets/recipe/
    - assets/user/
